// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_Storage_BulkAccess_H
#define WINRT_Windows_Storage_BulkAccess_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.Storage.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Storage.2.h"
#include "winrt/impl/Windows.Storage.FileProperties.2.h"
#include "winrt/impl/Windows.Storage.Search.2.h"
#include "winrt/impl/Windows.Storage.Streams.2.h"
#include "winrt/impl/Windows.Storage.BulkAccess.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetItemsAsync(std::uint32_t startIndex, std::uint32_t maxItemsToRetrieve) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetItemsAsync, startIndex, maxItemsToRetrieve, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetItemsAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetItemsAsyncDefaultStartAndCount, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetFilesAsync(std::uint32_t startIndex, std::uint32_t maxItemsToRetrieve) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetFilesAsync, startIndex, maxItemsToRetrieve, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FileInformation>>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetFilesAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetFilesAsyncDefaultStartAndCount, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FileInformation>>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetFoldersAsync(std::uint32_t startIndex, std::uint32_t maxItemsToRetrieve) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetFoldersAsync, startIndex, maxItemsToRetrieve, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FolderInformation>>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetFoldersAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetFoldersAsyncDefaultStartAndCount, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FolderInformation>>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetVirtualizedItemsVector() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetVirtualizedItemsVector, &winrt_impl_result);
        return winrt::Windows::Foundation::IInspectable{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetVirtualizedFilesVector() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetVirtualizedFilesVector, &winrt_impl_result);
        return winrt::Windows::Foundation::IInspectable{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactory<D>::GetVirtualizedFoldersVector() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactory>::GetVirtualizedFoldersVector, &winrt_impl_result);
        return winrt::Windows::Foundation::IInspectable{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactoryFactory<D>::CreateWithMode(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory>::CreateWithMode, *(void**)(&queryResult), static_cast<std::int32_t>(mode), &winrt_impl_result);
        return winrt::Windows::Storage::BulkAccess::FileInformationFactory{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactoryFactory<D>::CreateWithModeAndSize(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode, std::uint32_t requestedThumbnailSize) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory>::CreateWithModeAndSize, *(void**)(&queryResult), static_cast<std::int32_t>(mode), requestedThumbnailSize, &winrt_impl_result);
        return winrt::Windows::Storage::BulkAccess::FileInformationFactory{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactoryFactory<D>::CreateWithModeAndSizeAndOptions(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode, std::uint32_t requestedThumbnailSize, winrt::Windows::Storage::FileProperties::ThumbnailOptions const& thumbnailOptions) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory>::CreateWithModeAndSizeAndOptions, *(void**)(&queryResult), static_cast<std::int32_t>(mode), requestedThumbnailSize, static_cast<std::uint32_t>(thumbnailOptions), &winrt_impl_result);
        return winrt::Windows::Storage::BulkAccess::FileInformationFactory{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IFileInformationFactoryFactory<D>::CreateWithModeAndSizeAndOptionsAndFlags(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode, std::uint32_t requestedThumbnailSize, winrt::Windows::Storage::FileProperties::ThumbnailOptions const& thumbnailOptions, bool delayLoad) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory>::CreateWithModeAndSizeAndOptionsAndFlags, *(void**)(&queryResult), static_cast<std::int32_t>(mode), requestedThumbnailSize, static_cast<std::uint32_t>(thumbnailOptions), delayLoad, &winrt_impl_result);
        return winrt::Windows::Storage::BulkAccess::FileInformationFactory{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::MusicProperties() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::get_MusicProperties, &winrt_impl_result);
        return winrt::Windows::Storage::FileProperties::MusicProperties{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::VideoProperties() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::get_VideoProperties, &winrt_impl_result);
        return winrt::Windows::Storage::FileProperties::VideoProperties{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::ImageProperties() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::get_ImageProperties, &winrt_impl_result);
        return winrt::Windows::Storage::FileProperties::ImageProperties{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::DocumentProperties() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::get_DocumentProperties, &winrt_impl_result);
        return winrt::Windows::Storage::FileProperties::DocumentProperties{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::BasicProperties() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::get_BasicProperties, &winrt_impl_result);
        return winrt::Windows::Storage::FileProperties::BasicProperties{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::Thumbnail() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::get_Thumbnail, &winrt_impl_result);
        return winrt::Windows::Storage::FileProperties::StorageItemThumbnail{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::ThumbnailUpdated(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::add_ThumbnailUpdated, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::ThumbnailUpdated(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, ThumbnailUpdated_revoker>(this, ThumbnailUpdated(handler));
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::ThumbnailUpdated(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::remove_ThumbnailUpdated, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::PropertiesUpdated(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::add_PropertiesUpdated, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::PropertiesUpdated(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, PropertiesUpdated_revoker>(this, PropertiesUpdated(handler));
    }
    template <typename D> auto consume_Windows_Storage_BulkAccess_IStorageItemInformation<D>::PropertiesUpdated(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>::remove_PropertiesUpdated, impl::bind_in(token));
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Storage::BulkAccess::IFileInformationFactory> : produce_base<D, winrt::Windows::Storage::BulkAccess::IFileInformationFactory>
    {
        std::int32_t __stdcall GetItemsAsync(std::uint32_t startIndex, std::uint32_t maxItemsToRetrieve, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>>>(this->shim().GetItemsAsync(startIndex, maxItemsToRetrieve));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetItemsAsyncDefaultStartAndCount(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::IStorageItemInformation>>>(this->shim().GetItemsAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetFilesAsync(std::uint32_t startIndex, std::uint32_t maxItemsToRetrieve, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FileInformation>>>(this->shim().GetFilesAsync(startIndex, maxItemsToRetrieve));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetFilesAsyncDefaultStartAndCount(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FileInformation>>>(this->shim().GetFilesAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetFoldersAsync(std::uint32_t startIndex, std::uint32_t maxItemsToRetrieve, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FolderInformation>>>(this->shim().GetFoldersAsync(startIndex, maxItemsToRetrieve));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetFoldersAsyncDefaultStartAndCount(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Storage::BulkAccess::FolderInformation>>>(this->shim().GetFoldersAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetVirtualizedItemsVector(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IInspectable>(this->shim().GetVirtualizedItemsVector());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetVirtualizedFilesVector(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IInspectable>(this->shim().GetVirtualizedFilesVector());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetVirtualizedFoldersVector(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IInspectable>(this->shim().GetVirtualizedFoldersVector());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory> : produce_base<D, winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory>
    {
        std::int32_t __stdcall CreateWithMode(void* queryResult, std::int32_t mode, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::BulkAccess::FileInformationFactory>(this->shim().CreateWithMode(*reinterpret_cast<winrt::Windows::Storage::Search::IStorageQueryResultBase const*>(&queryResult), *reinterpret_cast<winrt::Windows::Storage::FileProperties::ThumbnailMode const*>(&mode)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall CreateWithModeAndSize(void* queryResult, std::int32_t mode, std::uint32_t requestedThumbnailSize, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::BulkAccess::FileInformationFactory>(this->shim().CreateWithModeAndSize(*reinterpret_cast<winrt::Windows::Storage::Search::IStorageQueryResultBase const*>(&queryResult), *reinterpret_cast<winrt::Windows::Storage::FileProperties::ThumbnailMode const*>(&mode), requestedThumbnailSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall CreateWithModeAndSizeAndOptions(void* queryResult, std::int32_t mode, std::uint32_t requestedThumbnailSize, std::uint32_t thumbnailOptions, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::BulkAccess::FileInformationFactory>(this->shim().CreateWithModeAndSizeAndOptions(*reinterpret_cast<winrt::Windows::Storage::Search::IStorageQueryResultBase const*>(&queryResult), *reinterpret_cast<winrt::Windows::Storage::FileProperties::ThumbnailMode const*>(&mode), requestedThumbnailSize, *reinterpret_cast<winrt::Windows::Storage::FileProperties::ThumbnailOptions const*>(&thumbnailOptions)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall CreateWithModeAndSizeAndOptionsAndFlags(void* queryResult, std::int32_t mode, std::uint32_t requestedThumbnailSize, std::uint32_t thumbnailOptions, bool delayLoad, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::BulkAccess::FileInformationFactory>(this->shim().CreateWithModeAndSizeAndOptionsAndFlags(*reinterpret_cast<winrt::Windows::Storage::Search::IStorageQueryResultBase const*>(&queryResult), *reinterpret_cast<winrt::Windows::Storage::FileProperties::ThumbnailMode const*>(&mode), requestedThumbnailSize, *reinterpret_cast<winrt::Windows::Storage::FileProperties::ThumbnailOptions const*>(&thumbnailOptions), delayLoad));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Storage::BulkAccess::IStorageItemInformation> : produce_base<D, winrt::Windows::Storage::BulkAccess::IStorageItemInformation>
    {
        std::int32_t __stdcall get_MusicProperties(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::FileProperties::MusicProperties>(this->shim().MusicProperties());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_VideoProperties(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::FileProperties::VideoProperties>(this->shim().VideoProperties());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ImageProperties(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::FileProperties::ImageProperties>(this->shim().ImageProperties());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DocumentProperties(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::FileProperties::DocumentProperties>(this->shim().DocumentProperties());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_BasicProperties(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::FileProperties::BasicProperties>(this->shim().BasicProperties());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Thumbnail(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::FileProperties::StorageItemThumbnail>(this->shim().Thumbnail());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_ThumbnailUpdated(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().ThumbnailUpdated(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_ThumbnailUpdated(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ThumbnailUpdated(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_PropertiesUpdated(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().PropertiesUpdated(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Storage::BulkAccess::IStorageItemInformation, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_PropertiesUpdated(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PropertiesUpdated(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
}
WINRT_EXPORT namespace winrt::Windows::Storage::BulkAccess
{
    inline FileInformationFactory::FileInformationFactory(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode) :
        FileInformationFactory(impl::call_factory<FileInformationFactory, IFileInformationFactoryFactory>([&](IFileInformationFactoryFactory const& f) { return f.CreateWithMode(queryResult, mode); }))
    {
    }
    inline FileInformationFactory::FileInformationFactory(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode, std::uint32_t requestedThumbnailSize) :
        FileInformationFactory(impl::call_factory<FileInformationFactory, IFileInformationFactoryFactory>([&](IFileInformationFactoryFactory const& f) { return f.CreateWithModeAndSize(queryResult, mode, requestedThumbnailSize); }))
    {
    }
    inline FileInformationFactory::FileInformationFactory(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode, std::uint32_t requestedThumbnailSize, winrt::Windows::Storage::FileProperties::ThumbnailOptions const& thumbnailOptions) :
        FileInformationFactory(impl::call_factory<FileInformationFactory, IFileInformationFactoryFactory>([&](IFileInformationFactoryFactory const& f) { return f.CreateWithModeAndSizeAndOptions(queryResult, mode, requestedThumbnailSize, thumbnailOptions); }))
    {
    }
    inline FileInformationFactory::FileInformationFactory(winrt::Windows::Storage::Search::IStorageQueryResultBase const& queryResult, winrt::Windows::Storage::FileProperties::ThumbnailMode const& mode, std::uint32_t requestedThumbnailSize, winrt::Windows::Storage::FileProperties::ThumbnailOptions const& thumbnailOptions, bool delayLoad) :
        FileInformationFactory(impl::call_factory<FileInformationFactory, IFileInformationFactoryFactory>([&](IFileInformationFactoryFactory const& f) { return f.CreateWithModeAndSizeAndOptionsAndFlags(queryResult, mode, requestedThumbnailSize, thumbnailOptions, delayLoad); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Storage::BulkAccess::IFileInformationFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Storage::BulkAccess::IFileInformationFactoryFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Storage::BulkAccess::IStorageItemInformation> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Storage::BulkAccess::FileInformation> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Storage::BulkAccess::FileInformationFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Storage::BulkAccess::FolderInformation> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
