// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_Media_Ocr_H
#define WINRT_Windows_Media_Ocr_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.Media.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Globalization.2.h"
#include "winrt/impl/Windows.Graphics.Imaging.2.h"
#include "winrt/impl/Windows.Media.Ocr.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngine<D>::RecognizeAsync(winrt::Windows::Graphics::Imaging::SoftwareBitmap const& bitmap) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngine, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngine>::RecognizeAsync, *(void**)(&bitmap), &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Ocr::OcrResult>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngine<D>::RecognizerLanguage() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngine, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngine>::get_RecognizerLanguage, &winrt_impl_result);
        return winrt::Windows::Globalization::Language{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngineStatics<D>::MaxImageDimension() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngineStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngineStatics>::get_MaxImageDimension, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngineStatics<D>::AvailableRecognizerLanguages() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngineStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngineStatics>::get_AvailableRecognizerLanguages, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Globalization::Language>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngineStatics<D>::IsLanguageSupported(winrt::Windows::Globalization::Language const& language) const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngineStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngineStatics>::IsLanguageSupported, *(void**)(&language), &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngineStatics<D>::TryCreateFromLanguage(winrt::Windows::Globalization::Language const& language) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngineStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngineStatics>::TryCreateFromLanguage, *(void**)(&language), &winrt_impl_result);
        return winrt::Windows::Media::Ocr::OcrEngine{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrEngineStatics<D>::TryCreateFromUserProfileLanguages() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrEngineStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrEngineStatics>::TryCreateFromUserProfileLanguages, &winrt_impl_result);
        return winrt::Windows::Media::Ocr::OcrEngine{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrLine<D>::Words() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrLine, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrLine>::get_Words, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::Ocr::OcrWord>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrLine<D>::Text() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrLine, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrLine>::get_Text, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrResult<D>::Lines() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrResult, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrResult>::get_Lines, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::Ocr::OcrLine>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrResult<D>::TextAngle() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrResult, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrResult>::get_TextAngle, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<double>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrResult<D>::Text() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrResult, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrResult>::get_Text, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrWord<D>::BoundingRect() const
    {
        winrt::Windows::Foundation::Rect winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrWord, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrWord>::get_BoundingRect, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Ocr_IOcrWord<D>::Text() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Ocr::IOcrWord, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Ocr::IOcrWord>::get_Text, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Ocr::IOcrEngine> : produce_base<D, winrt::Windows::Media::Ocr::IOcrEngine>
    {
        std::int32_t __stdcall RecognizeAsync(void* bitmap, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Ocr::OcrResult>>(this->shim().RecognizeAsync(*reinterpret_cast<winrt::Windows::Graphics::Imaging::SoftwareBitmap const*>(&bitmap)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_RecognizerLanguage(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Globalization::Language>(this->shim().RecognizerLanguage());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Ocr::IOcrEngineStatics> : produce_base<D, winrt::Windows::Media::Ocr::IOcrEngineStatics>
    {
        std::int32_t __stdcall get_MaxImageDimension(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().MaxImageDimension());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_AvailableRecognizerLanguages(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Globalization::Language>>(this->shim().AvailableRecognizerLanguages());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall IsLanguageSupported(void* language, bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsLanguageSupported(*reinterpret_cast<winrt::Windows::Globalization::Language const*>(&language)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryCreateFromLanguage(void* language, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Ocr::OcrEngine>(this->shim().TryCreateFromLanguage(*reinterpret_cast<winrt::Windows::Globalization::Language const*>(&language)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryCreateFromUserProfileLanguages(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Ocr::OcrEngine>(this->shim().TryCreateFromUserProfileLanguages());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Ocr::IOcrLine> : produce_base<D, winrt::Windows::Media::Ocr::IOcrLine>
    {
        std::int32_t __stdcall get_Words(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::Ocr::OcrWord>>(this->shim().Words());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Text(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Text());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Ocr::IOcrResult> : produce_base<D, winrt::Windows::Media::Ocr::IOcrResult>
    {
        std::int32_t __stdcall get_Lines(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::Ocr::OcrLine>>(this->shim().Lines());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_TextAngle(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<double>>(this->shim().TextAngle());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Text(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Text());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Ocr::IOcrWord> : produce_base<D, winrt::Windows::Media::Ocr::IOcrWord>
    {
        std::int32_t __stdcall get_BoundingRect(winrt::Windows::Foundation::Rect* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Rect>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Rect>(this->shim().BoundingRect());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Text(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Text());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Media::Ocr
{
    inline auto OcrEngine::MaxImageDimension()
    {
        return impl::call_factory_cast<std::uint32_t(*)(IOcrEngineStatics const&), OcrEngine, IOcrEngineStatics>([](IOcrEngineStatics const& f) { return f.MaxImageDimension(); });
    }
    inline auto OcrEngine::AvailableRecognizerLanguages()
    {
        return impl::call_factory_cast<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Globalization::Language>(*)(IOcrEngineStatics const&), OcrEngine, IOcrEngineStatics>([](IOcrEngineStatics const& f) { return f.AvailableRecognizerLanguages(); });
    }
    inline auto OcrEngine::IsLanguageSupported(winrt::Windows::Globalization::Language const& language)
    {
        return impl::call_factory<OcrEngine, IOcrEngineStatics>([&](IOcrEngineStatics const& f) { return f.IsLanguageSupported(language); });
    }
    inline auto OcrEngine::TryCreateFromLanguage(winrt::Windows::Globalization::Language const& language)
    {
        return impl::call_factory<OcrEngine, IOcrEngineStatics>([&](IOcrEngineStatics const& f) { return f.TryCreateFromLanguage(language); });
    }
    inline auto OcrEngine::TryCreateFromUserProfileLanguages()
    {
        return impl::call_factory_cast<winrt::Windows::Media::Ocr::OcrEngine(*)(IOcrEngineStatics const&), OcrEngine, IOcrEngineStatics>([](IOcrEngineStatics const& f) { return f.TryCreateFromUserProfileLanguages(); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Media::Ocr::IOcrEngine> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::IOcrEngineStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::IOcrLine> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::IOcrResult> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::IOcrWord> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::OcrEngine> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::OcrLine> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::OcrResult> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Ocr::OcrWord> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
