// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_Devices_SerialCommunication_H
#define WINRT_Windows_Devices_SerialCommunication_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.Devices.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Storage.Streams.2.h"
#include "winrt/impl/Windows.Devices.SerialCommunication.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Devices_SerialCommunication_IErrorReceivedEventArgs<D>::Error() const
    {
        winrt::Windows::Devices::SerialCommunication::SerialError winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::IErrorReceivedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::IErrorReceivedEventArgs>::get_Error, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_IPinChangedEventArgs<D>::PinChange() const
    {
        winrt::Windows::Devices::SerialCommunication::SerialPinChange winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::IPinChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::IPinChangedEventArgs>::get_PinChange, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::BaudRate() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_BaudRate, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::BaudRate(std::uint32_t value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_BaudRate, value);
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::BreakSignalState() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_BreakSignalState, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::BreakSignalState(bool value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_BreakSignalState, value);
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::BytesReceived() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_BytesReceived, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::CarrierDetectState() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_CarrierDetectState, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::ClearToSendState() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_ClearToSendState, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::DataBits() const
    {
        std::uint16_t winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_DataBits, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::DataBits(std::uint16_t value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_DataBits, value);
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::DataSetReadyState() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_DataSetReadyState, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::Handshake() const
    {
        winrt::Windows::Devices::SerialCommunication::SerialHandshake winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_Handshake, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::Handshake(winrt::Windows::Devices::SerialCommunication::SerialHandshake const& value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_Handshake, static_cast<std::int32_t>(value));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::IsDataTerminalReadyEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_IsDataTerminalReadyEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::IsDataTerminalReadyEnabled(bool value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_IsDataTerminalReadyEnabled, value);
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::IsRequestToSendEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_IsRequestToSendEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::IsRequestToSendEnabled(bool value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_IsRequestToSendEnabled, value);
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::Parity() const
    {
        winrt::Windows::Devices::SerialCommunication::SerialParity winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_Parity, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::Parity(winrt::Windows::Devices::SerialCommunication::SerialParity const& value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_Parity, static_cast<std::int32_t>(value));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::PortName() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_PortName, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::ReadTimeout() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_ReadTimeout, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::ReadTimeout(winrt::Windows::Foundation::TimeSpan const& value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_ReadTimeout, impl::bind_in(value));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::StopBits() const
    {
        winrt::Windows::Devices::SerialCommunication::SerialStopBitCount winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_StopBits, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::StopBits(winrt::Windows::Devices::SerialCommunication::SerialStopBitCount const& value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_StopBits, static_cast<std::int32_t>(value));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::UsbVendorId() const
    {
        std::uint16_t winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_UsbVendorId, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::UsbProductId() const
    {
        std::uint16_t winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_UsbProductId, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::WriteTimeout() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_WriteTimeout, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::WriteTimeout(winrt::Windows::Foundation::TimeSpan const& value) const
    {
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::put_WriteTimeout, impl::bind_in(value));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::InputStream() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_InputStream, &winrt_impl_result);
        return winrt::Windows::Storage::Streams::IInputStream{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::OutputStream() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::get_OutputStream, &winrt_impl_result);
        return winrt::Windows::Storage::Streams::IOutputStream{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::ErrorReceived(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Devices::SerialCommunication::SerialDevice, winrt::Windows::Devices::SerialCommunication::ErrorReceivedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::add_ErrorReceived, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::ErrorReceived(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Devices::SerialCommunication::SerialDevice, winrt::Windows::Devices::SerialCommunication::ErrorReceivedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, ErrorReceived_revoker>(this, ErrorReceived(handler));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::ErrorReceived(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::remove_ErrorReceived, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::PinChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Devices::SerialCommunication::SerialDevice, winrt::Windows::Devices::SerialCommunication::PinChangedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::add_PinChanged, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::PinChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Devices::SerialCommunication::SerialDevice, winrt::Windows::Devices::SerialCommunication::PinChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, PinChanged_revoker>(this, PinChanged(handler));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDevice<D>::PinChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Devices::SerialCommunication::ISerialDevice, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDevice>::remove_PinChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDeviceStatics<D>::GetDeviceSelector() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics>::GetDeviceSelector, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDeviceStatics<D>::GetDeviceSelector(param::hstring const& portName) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics>::GetDeviceSelectorFromPortName, *(void**)(&portName), &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDeviceStatics<D>::GetDeviceSelectorFromUsbVidPid(std::uint16_t vendorId, std::uint16_t productId) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics>::GetDeviceSelectorFromUsbVidPid, vendorId, productId, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Devices_SerialCommunication_ISerialDeviceStatics<D>::FromIdAsync(param::hstring const& deviceId) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics>::FromIdAsync, *(void**)(&deviceId), &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Devices::SerialCommunication::SerialDevice>{ winrt_impl_result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Devices::SerialCommunication::IErrorReceivedEventArgs> : produce_base<D, winrt::Windows::Devices::SerialCommunication::IErrorReceivedEventArgs>
    {
        std::int32_t __stdcall get_Error(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Devices::SerialCommunication::SerialError>(this->shim().Error());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Devices::SerialCommunication::IPinChangedEventArgs> : produce_base<D, winrt::Windows::Devices::SerialCommunication::IPinChangedEventArgs>
    {
        std::int32_t __stdcall get_PinChange(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Devices::SerialCommunication::SerialPinChange>(this->shim().PinChange());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Devices::SerialCommunication::ISerialDevice> : produce_base<D, winrt::Windows::Devices::SerialCommunication::ISerialDevice>
    {
        std::int32_t __stdcall get_BaudRate(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().BaudRate());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_BaudRate(std::uint32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().BaudRate(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_BreakSignalState(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().BreakSignalState());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_BreakSignalState(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().BreakSignalState(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_BytesReceived(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().BytesReceived());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_CarrierDetectState(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().CarrierDetectState());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ClearToSendState(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().ClearToSendState());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DataBits(std::uint16_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint16_t>(this->shim().DataBits());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_DataBits(std::uint16_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DataBits(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DataSetReadyState(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().DataSetReadyState());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Handshake(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Devices::SerialCommunication::SerialHandshake>(this->shim().Handshake());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Handshake(std::int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Handshake(*reinterpret_cast<winrt::Windows::Devices::SerialCommunication::SerialHandshake const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsDataTerminalReadyEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsDataTerminalReadyEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_IsDataTerminalReadyEnabled(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsDataTerminalReadyEnabled(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsRequestToSendEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsRequestToSendEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_IsRequestToSendEnabled(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsRequestToSendEnabled(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Parity(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Devices::SerialCommunication::SerialParity>(this->shim().Parity());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Parity(std::int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Parity(*reinterpret_cast<winrt::Windows::Devices::SerialCommunication::SerialParity const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PortName(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().PortName());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ReadTimeout(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().ReadTimeout());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_ReadTimeout(std::int64_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ReadTimeout(*reinterpret_cast<winrt::Windows::Foundation::TimeSpan const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_StopBits(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Devices::SerialCommunication::SerialStopBitCount>(this->shim().StopBits());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_StopBits(std::int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().StopBits(*reinterpret_cast<winrt::Windows::Devices::SerialCommunication::SerialStopBitCount const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_UsbVendorId(std::uint16_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint16_t>(this->shim().UsbVendorId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_UsbProductId(std::uint16_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint16_t>(this->shim().UsbProductId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_WriteTimeout(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().WriteTimeout());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_WriteTimeout(std::int64_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().WriteTimeout(*reinterpret_cast<winrt::Windows::Foundation::TimeSpan const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_InputStream(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::Streams::IInputStream>(this->shim().InputStream());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_OutputStream(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::Streams::IOutputStream>(this->shim().OutputStream());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_ErrorReceived(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().ErrorReceived(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Devices::SerialCommunication::SerialDevice, winrt::Windows::Devices::SerialCommunication::ErrorReceivedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_ErrorReceived(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ErrorReceived(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_PinChanged(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().PinChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Devices::SerialCommunication::SerialDevice, winrt::Windows::Devices::SerialCommunication::PinChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_PinChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PinChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics> : produce_base<D, winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics>
    {
        std::int32_t __stdcall GetDeviceSelector(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().GetDeviceSelector());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetDeviceSelectorFromPortName(void* portName, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().GetDeviceSelector(*reinterpret_cast<hstring const*>(&portName)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetDeviceSelectorFromUsbVidPid(std::uint16_t vendorId, std::uint16_t productId, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().GetDeviceSelectorFromUsbVidPid(vendorId, productId));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall FromIdAsync(void* deviceId, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Devices::SerialCommunication::SerialDevice>>(this->shim().FromIdAsync(*reinterpret_cast<hstring const*>(&deviceId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Devices::SerialCommunication
{
    inline auto SerialDevice::GetDeviceSelector()
    {
        return impl::call_factory_cast<hstring(*)(ISerialDeviceStatics const&), SerialDevice, ISerialDeviceStatics>([](ISerialDeviceStatics const& f) { return f.GetDeviceSelector(); });
    }
    inline auto SerialDevice::GetDeviceSelector(param::hstring const& portName)
    {
        return impl::call_factory<SerialDevice, ISerialDeviceStatics>([&](ISerialDeviceStatics const& f) { return f.GetDeviceSelector(portName); });
    }
    inline auto SerialDevice::GetDeviceSelectorFromUsbVidPid(std::uint16_t vendorId, std::uint16_t productId)
    {
        return impl::call_factory<SerialDevice, ISerialDeviceStatics>([&](ISerialDeviceStatics const& f) { return f.GetDeviceSelectorFromUsbVidPid(vendorId, productId); });
    }
    inline auto SerialDevice::FromIdAsync(param::hstring const& deviceId)
    {
        return impl::call_factory<SerialDevice, ISerialDeviceStatics>([&](ISerialDeviceStatics const& f) { return f.FromIdAsync(deviceId); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::IErrorReceivedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::IPinChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::ISerialDevice> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::ISerialDeviceStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::ErrorReceivedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::PinChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Devices::SerialCommunication::SerialDevice> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
