// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_Media_Devices_Core_H
#define WINRT_Windows_Media_Devices_Core_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.Media.Devices.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Foundation.Numerics.2.h"
#include "winrt/impl/Windows.Media.MediaProperties.2.h"
#include "winrt/impl/Windows.Perception.Spatial.2.h"
#include "winrt/impl/Windows.Media.Devices.Core.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::FocalLength() const
    {
        winrt::Windows::Foundation::Numerics::float2 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::get_FocalLength, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::PrincipalPoint() const
    {
        winrt::Windows::Foundation::Numerics::float2 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::get_PrincipalPoint, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::RadialDistortion() const
    {
        winrt::Windows::Foundation::Numerics::float3 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::get_RadialDistortion, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::TangentialDistortion() const
    {
        winrt::Windows::Foundation::Numerics::float2 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::get_TangentialDistortion, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::ImageWidth() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::get_ImageWidth, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::ImageHeight() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::get_ImageHeight, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::ProjectOntoFrame(winrt::Windows::Foundation::Numerics::float3 const& coordinate) const
    {
        winrt::Windows::Foundation::Point winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::ProjectOntoFrame, impl::bind_in(coordinate), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::UnprojectAtUnitDepth(winrt::Windows::Foundation::Point const& pixelCoordinate) const
    {
        winrt::Windows::Foundation::Numerics::float2 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::UnprojectAtUnitDepth, impl::bind_in(pixelCoordinate), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::ProjectManyOntoFrame(array_view<winrt::Windows::Foundation::Numerics::float3 const> coordinates, array_view<winrt::Windows::Foundation::Point> results) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::ProjectManyOntoFrame, coordinates.size(), get_abi(coordinates), results.size(), put_abi(results));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics<D>::UnprojectPixelsAtUnitDepth(array_view<winrt::Windows::Foundation::Point const> pixelCoordinates, array_view<winrt::Windows::Foundation::Numerics::float2> results) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics>::UnprojectPixelsAtUnitDepth, pixelCoordinates.size(), get_abi(pixelCoordinates), results.size(), put_abi(results));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics2<D>::UndistortedProjectionTransform() const
    {
        winrt::Windows::Foundation::Numerics::float4x4 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2>::get_UndistortedProjectionTransform, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics2<D>::DistortPoint(winrt::Windows::Foundation::Point const& input) const
    {
        winrt::Windows::Foundation::Point winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2>::DistortPoint, impl::bind_in(input), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics2<D>::DistortPoints(array_view<winrt::Windows::Foundation::Point const> inputs, array_view<winrt::Windows::Foundation::Point> results) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2>::DistortPoints, inputs.size(), get_abi(inputs), results.size(), put_abi(results));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics2<D>::UndistortPoint(winrt::Windows::Foundation::Point const& input) const
    {
        winrt::Windows::Foundation::Point winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2>::UndistortPoint, impl::bind_in(input), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsics2<D>::UndistortPoints(array_view<winrt::Windows::Foundation::Point const> inputs, array_view<winrt::Windows::Foundation::Point> results) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2>::UndistortPoints, inputs.size(), get_abi(inputs), results.size(), put_abi(results));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_ICameraIntrinsicsFactory<D>::Create(winrt::Windows::Foundation::Numerics::float2 const& focalLength, winrt::Windows::Foundation::Numerics::float2 const& principalPoint, winrt::Windows::Foundation::Numerics::float3 const& radialDistortion, winrt::Windows::Foundation::Numerics::float2 const& tangentialDistortion, std::uint32_t imageWidth, std::uint32_t imageHeight) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::ICameraIntrinsicsFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::ICameraIntrinsicsFactory>::Create, impl::bind_in(focalLength), impl::bind_in(principalPoint), impl::bind_in(radialDistortion), impl::bind_in(tangentialDistortion), imageWidth, imageHeight, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::CameraIntrinsics{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IDepthCorrelatedCoordinateMapper<D>::UnprojectPoint(winrt::Windows::Foundation::Point const& sourcePoint, winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const& targetCoordinateSystem) const
    {
        winrt::Windows::Foundation::Numerics::float3 winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper>::UnprojectPoint, impl::bind_in(sourcePoint), *(void**)(&targetCoordinateSystem), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IDepthCorrelatedCoordinateMapper<D>::UnprojectPoints(array_view<winrt::Windows::Foundation::Point const> sourcePoints, winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const& targetCoordinateSystem, array_view<winrt::Windows::Foundation::Numerics::float3> results) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper>::UnprojectPoints, sourcePoints.size(), get_abi(sourcePoints), *(void**)(&targetCoordinateSystem), results.size(), put_abi(results));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IDepthCorrelatedCoordinateMapper<D>::MapPoint(winrt::Windows::Foundation::Point const& sourcePoint, winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const& targetCoordinateSystem, winrt::Windows::Media::Devices::Core::CameraIntrinsics const& targetCameraIntrinsics) const
    {
        winrt::Windows::Foundation::Point winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper>::MapPoint, impl::bind_in(sourcePoint), *(void**)(&targetCoordinateSystem), *(void**)(&targetCameraIntrinsics), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IDepthCorrelatedCoordinateMapper<D>::MapPoints(array_view<winrt::Windows::Foundation::Point const> sourcePoints, winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const& targetCoordinateSystem, winrt::Windows::Media::Devices::Core::CameraIntrinsics const& targetCameraIntrinsics, array_view<winrt::Windows::Foundation::Point> results) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper>::MapPoints, sourcePoints.size(), get_abi(sourcePoints), *(void**)(&targetCoordinateSystem), *(void**)(&targetCameraIntrinsics), results.size(), put_abi(results));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameControlCapabilities<D>::Exposure() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities>::get_Exposure, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameExposureCapabilities{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameControlCapabilities<D>::ExposureCompensation() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities>::get_ExposureCompensation, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameExposureCompensationCapabilities{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameControlCapabilities<D>::IsoSpeed() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities>::get_IsoSpeed, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameIsoSpeedCapabilities{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameControlCapabilities<D>::Focus() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities>::get_Focus, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameFocusCapabilities{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameControlCapabilities<D>::PhotoConfirmationSupported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities>::get_PhotoConfirmationSupported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameControlCapabilities2<D>::Flash() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities2>::get_Flash, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameFlashCapabilities{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController<D>::ExposureControl() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController>::get_ExposureControl, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameExposureControl{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController<D>::ExposureCompensationControl() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController>::get_ExposureCompensationControl, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameExposureCompensationControl{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController<D>::IsoSpeedControl() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController>::get_IsoSpeedControl, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameIsoSpeedControl{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController<D>::FocusControl() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController>::get_FocusControl, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameFocusControl{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController<D>::PhotoConfirmationEnabled() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController>::get_PhotoConfirmationEnabled, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController<D>::PhotoConfirmationEnabled(winrt::Windows::Foundation::IReference<bool> const& value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController>::put_PhotoConfirmationEnabled, *(void**)(&value));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameController2<D>::FlashControl() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameController2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameController2>::get_FlashControl, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameFlashControl{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCapabilities<D>::Supported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities>::get_Supported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCapabilities<D>::Min() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities>::get_Min, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCapabilities<D>::Max() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities>::get_Max, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCapabilities<D>::Step() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities>::get_Step, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCompensationCapabilities<D>::Supported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities>::get_Supported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCompensationCapabilities<D>::Min() const
    {
        float winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities>::get_Min, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCompensationCapabilities<D>::Max() const
    {
        float winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities>::get_Max, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCompensationCapabilities<D>::Step() const
    {
        float winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities>::get_Step, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCompensationControl<D>::Value() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl>::get_Value, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<float>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureCompensationControl<D>::Value(winrt::Windows::Foundation::IReference<float> const& value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl>::put_Value, *(void**)(&value));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureControl<D>::Auto() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureControl>::get_Auto, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureControl<D>::Auto(bool value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureControl>::put_Auto, value);
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureControl<D>::Value() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureControl>::get_Value, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<winrt::Windows::Foundation::TimeSpan>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameExposureControl<D>::Value(winrt::Windows::Foundation::IReference<winrt::Windows::Foundation::TimeSpan> const& value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameExposureControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameExposureControl>::put_Value, *(void**)(&value));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashCapabilities<D>::Supported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities>::get_Supported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashCapabilities<D>::RedEyeReductionSupported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities>::get_RedEyeReductionSupported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashCapabilities<D>::PowerSupported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities>::get_PowerSupported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::Mode() const
    {
        winrt::Windows::Media::Devices::Core::FrameFlashMode winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::get_Mode, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::Mode(winrt::Windows::Media::Devices::Core::FrameFlashMode const& value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::put_Mode, static_cast<std::int32_t>(value));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::Auto() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::get_Auto, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::Auto(bool value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::put_Auto, value);
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::RedEyeReduction() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::get_RedEyeReduction, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::RedEyeReduction(bool value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::put_RedEyeReduction, value);
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::PowerPercent() const
    {
        float winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::get_PowerPercent, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFlashControl<D>::PowerPercent(float value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFlashControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFlashControl>::put_PowerPercent, value);
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFocusCapabilities<D>::Supported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities>::get_Supported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFocusCapabilities<D>::Min() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities>::get_Min, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFocusCapabilities<D>::Max() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities>::get_Max, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFocusCapabilities<D>::Step() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities>::get_Step, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFocusControl<D>::Value() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFocusControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFocusControl>::get_Value, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<std::uint32_t>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameFocusControl<D>::Value(winrt::Windows::Foundation::IReference<std::uint32_t> const& value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameFocusControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameFocusControl>::put_Value, *(void**)(&value));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedCapabilities<D>::Supported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities>::get_Supported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedCapabilities<D>::Min() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities>::get_Min, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedCapabilities<D>::Max() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities>::get_Max, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedCapabilities<D>::Step() const
    {
        std::uint32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities>::get_Step, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedControl<D>::Auto() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl>::get_Auto, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedControl<D>::Auto(bool value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl>::put_Auto, value);
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedControl<D>::Value() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl>::get_Value, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<std::uint32_t>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IFrameIsoSpeedControl<D>::Value(winrt::Windows::Foundation::IReference<std::uint32_t> const& value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl>::put_Value, *(void**)(&value));
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::Supported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::get_Supported, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::MaxPhotosPerSecond() const
    {
        float winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::get_MaxPhotosPerSecond, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::PhotosPerSecondLimit() const
    {
        float winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::get_PhotosPerSecondLimit, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::PhotosPerSecondLimit(float value) const
    {
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::put_PhotosPerSecondLimit, value);
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::GetHighestConcurrentFrameRate(winrt::Windows::Media::MediaProperties::IMediaEncodingProperties const& captureProperties) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::GetHighestConcurrentFrameRate, *(void**)(&captureProperties), &winrt_impl_result);
        return winrt::Windows::Media::MediaProperties::MediaRatio{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::GetCurrentFrameRate() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::GetCurrentFrameRate, &winrt_impl_result);
        return winrt::Windows::Media::MediaProperties::MediaRatio{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::FrameCapabilities() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::get_FrameCapabilities, &winrt_impl_result);
        return winrt::Windows::Media::Devices::Core::FrameControlCapabilities{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Devices_Core_IVariablePhotoSequenceController<D>::DesiredFrameControllers() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>::get_DesiredFrameControllers, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVector<winrt::Windows::Media::Devices::Core::FrameController>{ winrt_impl_result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::ICameraIntrinsics> : produce_base<D, winrt::Windows::Media::Devices::Core::ICameraIntrinsics>
    {
        std::int32_t __stdcall get_FocalLength(winrt::Windows::Foundation::Numerics::float2* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float2>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float2>(this->shim().FocalLength());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PrincipalPoint(winrt::Windows::Foundation::Numerics::float2* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float2>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float2>(this->shim().PrincipalPoint());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_RadialDistortion(winrt::Windows::Foundation::Numerics::float3* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float3>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float3>(this->shim().RadialDistortion());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_TangentialDistortion(winrt::Windows::Foundation::Numerics::float2* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float2>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float2>(this->shim().TangentialDistortion());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ImageWidth(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().ImageWidth());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ImageHeight(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().ImageHeight());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall ProjectOntoFrame(winrt::Windows::Foundation::Numerics::float3 coordinate, winrt::Windows::Foundation::Point* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Point>(this->shim().ProjectOntoFrame(*reinterpret_cast<winrt::Windows::Foundation::Numerics::float3 const*>(&coordinate)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall UnprojectAtUnitDepth(winrt::Windows::Foundation::Point pixelCoordinate, winrt::Windows::Foundation::Numerics::float2* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float2>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float2>(this->shim().UnprojectAtUnitDepth(*reinterpret_cast<winrt::Windows::Foundation::Point const*>(&pixelCoordinate)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall ProjectManyOntoFrame(std::uint32_t __coordinatesSize, winrt::Windows::Foundation::Numerics::float3* coordinates, std::uint32_t __resultsSize, winrt::Windows::Foundation::Point* results) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(results, __resultsSize);
            typename D::abi_guard guard(this->shim());
            this->shim().ProjectManyOntoFrame(array_view<winrt::Windows::Foundation::Numerics::float3 const>(reinterpret_cast<winrt::Windows::Foundation::Numerics::float3 const *>(coordinates), reinterpret_cast<winrt::Windows::Foundation::Numerics::float3 const *>(coordinates) + __coordinatesSize), array_view<winrt::Windows::Foundation::Point>(reinterpret_cast<winrt::Windows::Foundation::Point*>(results), reinterpret_cast<winrt::Windows::Foundation::Point*>(results) + __resultsSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall UnprojectPixelsAtUnitDepth(std::uint32_t __pixelCoordinatesSize, winrt::Windows::Foundation::Point* pixelCoordinates, std::uint32_t __resultsSize, winrt::Windows::Foundation::Numerics::float2* results) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float2>(results, __resultsSize);
            typename D::abi_guard guard(this->shim());
            this->shim().UnprojectPixelsAtUnitDepth(array_view<winrt::Windows::Foundation::Point const>(reinterpret_cast<winrt::Windows::Foundation::Point const *>(pixelCoordinates), reinterpret_cast<winrt::Windows::Foundation::Point const *>(pixelCoordinates) + __pixelCoordinatesSize), array_view<winrt::Windows::Foundation::Numerics::float2>(reinterpret_cast<winrt::Windows::Foundation::Numerics::float2*>(results), reinterpret_cast<winrt::Windows::Foundation::Numerics::float2*>(results) + __resultsSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::ICameraIntrinsics2> : produce_base<D, winrt::Windows::Media::Devices::Core::ICameraIntrinsics2>
    {
        std::int32_t __stdcall get_UndistortedProjectionTransform(winrt::Windows::Foundation::Numerics::float4x4* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float4x4>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float4x4>(this->shim().UndistortedProjectionTransform());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall DistortPoint(winrt::Windows::Foundation::Point input, winrt::Windows::Foundation::Point* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Point>(this->shim().DistortPoint(*reinterpret_cast<winrt::Windows::Foundation::Point const*>(&input)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall DistortPoints(std::uint32_t __inputsSize, winrt::Windows::Foundation::Point* inputs, std::uint32_t __resultsSize, winrt::Windows::Foundation::Point* results) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(results, __resultsSize);
            typename D::abi_guard guard(this->shim());
            this->shim().DistortPoints(array_view<winrt::Windows::Foundation::Point const>(reinterpret_cast<winrt::Windows::Foundation::Point const *>(inputs), reinterpret_cast<winrt::Windows::Foundation::Point const *>(inputs) + __inputsSize), array_view<winrt::Windows::Foundation::Point>(reinterpret_cast<winrt::Windows::Foundation::Point*>(results), reinterpret_cast<winrt::Windows::Foundation::Point*>(results) + __resultsSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall UndistortPoint(winrt::Windows::Foundation::Point input, winrt::Windows::Foundation::Point* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Point>(this->shim().UndistortPoint(*reinterpret_cast<winrt::Windows::Foundation::Point const*>(&input)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall UndistortPoints(std::uint32_t __inputsSize, winrt::Windows::Foundation::Point* inputs, std::uint32_t __resultsSize, winrt::Windows::Foundation::Point* results) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(results, __resultsSize);
            typename D::abi_guard guard(this->shim());
            this->shim().UndistortPoints(array_view<winrt::Windows::Foundation::Point const>(reinterpret_cast<winrt::Windows::Foundation::Point const *>(inputs), reinterpret_cast<winrt::Windows::Foundation::Point const *>(inputs) + __inputsSize), array_view<winrt::Windows::Foundation::Point>(reinterpret_cast<winrt::Windows::Foundation::Point*>(results), reinterpret_cast<winrt::Windows::Foundation::Point*>(results) + __resultsSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::ICameraIntrinsicsFactory> : produce_base<D, winrt::Windows::Media::Devices::Core::ICameraIntrinsicsFactory>
    {
        std::int32_t __stdcall Create(winrt::Windows::Foundation::Numerics::float2 focalLength, winrt::Windows::Foundation::Numerics::float2 principalPoint, winrt::Windows::Foundation::Numerics::float3 radialDistortion, winrt::Windows::Foundation::Numerics::float2 tangentialDistortion, std::uint32_t imageWidth, std::uint32_t imageHeight, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::CameraIntrinsics>(this->shim().Create(*reinterpret_cast<winrt::Windows::Foundation::Numerics::float2 const*>(&focalLength), *reinterpret_cast<winrt::Windows::Foundation::Numerics::float2 const*>(&principalPoint), *reinterpret_cast<winrt::Windows::Foundation::Numerics::float3 const*>(&radialDistortion), *reinterpret_cast<winrt::Windows::Foundation::Numerics::float2 const*>(&tangentialDistortion), imageWidth, imageHeight));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper> : produce_base<D, winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper>
    {
        std::int32_t __stdcall UnprojectPoint(winrt::Windows::Foundation::Point sourcePoint, void* targetCoordinateSystem, winrt::Windows::Foundation::Numerics::float3* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float3>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Numerics::float3>(this->shim().UnprojectPoint(*reinterpret_cast<winrt::Windows::Foundation::Point const*>(&sourcePoint), *reinterpret_cast<winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const*>(&targetCoordinateSystem)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall UnprojectPoints(std::uint32_t __sourcePointsSize, winrt::Windows::Foundation::Point* sourcePoints, void* targetCoordinateSystem, std::uint32_t __resultsSize, winrt::Windows::Foundation::Numerics::float3* results) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float3>(results, __resultsSize);
            typename D::abi_guard guard(this->shim());
            this->shim().UnprojectPoints(array_view<winrt::Windows::Foundation::Point const>(reinterpret_cast<winrt::Windows::Foundation::Point const *>(sourcePoints), reinterpret_cast<winrt::Windows::Foundation::Point const *>(sourcePoints) + __sourcePointsSize), *reinterpret_cast<winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const*>(&targetCoordinateSystem), array_view<winrt::Windows::Foundation::Numerics::float3>(reinterpret_cast<winrt::Windows::Foundation::Numerics::float3*>(results), reinterpret_cast<winrt::Windows::Foundation::Numerics::float3*>(results) + __resultsSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall MapPoint(winrt::Windows::Foundation::Point sourcePoint, void* targetCoordinateSystem, void* targetCameraIntrinsics, winrt::Windows::Foundation::Point* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Point>(this->shim().MapPoint(*reinterpret_cast<winrt::Windows::Foundation::Point const*>(&sourcePoint), *reinterpret_cast<winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const*>(&targetCoordinateSystem), *reinterpret_cast<winrt::Windows::Media::Devices::Core::CameraIntrinsics const*>(&targetCameraIntrinsics)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall MapPoints(std::uint32_t __sourcePointsSize, winrt::Windows::Foundation::Point* sourcePoints, void* targetCoordinateSystem, void* targetCameraIntrinsics, std::uint32_t __resultsSize, winrt::Windows::Foundation::Point* results) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Point>(results, __resultsSize);
            typename D::abi_guard guard(this->shim());
            this->shim().MapPoints(array_view<winrt::Windows::Foundation::Point const>(reinterpret_cast<winrt::Windows::Foundation::Point const *>(sourcePoints), reinterpret_cast<winrt::Windows::Foundation::Point const *>(sourcePoints) + __sourcePointsSize), *reinterpret_cast<winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const*>(&targetCoordinateSystem), *reinterpret_cast<winrt::Windows::Media::Devices::Core::CameraIntrinsics const*>(&targetCameraIntrinsics), array_view<winrt::Windows::Foundation::Point>(reinterpret_cast<winrt::Windows::Foundation::Point*>(results), reinterpret_cast<winrt::Windows::Foundation::Point*>(results) + __resultsSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameControlCapabilities> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameControlCapabilities>
    {
        std::int32_t __stdcall get_Exposure(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameExposureCapabilities>(this->shim().Exposure());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ExposureCompensation(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameExposureCompensationCapabilities>(this->shim().ExposureCompensation());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsoSpeed(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameIsoSpeedCapabilities>(this->shim().IsoSpeed());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Focus(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameFocusCapabilities>(this->shim().Focus());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PhotoConfirmationSupported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().PhotoConfirmationSupported());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameControlCapabilities2> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameControlCapabilities2>
    {
        std::int32_t __stdcall get_Flash(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameFlashCapabilities>(this->shim().Flash());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameController> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameController>
    {
        std::int32_t __stdcall get_ExposureControl(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameExposureControl>(this->shim().ExposureControl());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ExposureCompensationControl(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameExposureCompensationControl>(this->shim().ExposureCompensationControl());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsoSpeedControl(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameIsoSpeedControl>(this->shim().IsoSpeedControl());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_FocusControl(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameFocusControl>(this->shim().FocusControl());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PhotoConfirmationEnabled(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<bool>>(this->shim().PhotoConfirmationEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_PhotoConfirmationEnabled(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PhotoConfirmationEnabled(*reinterpret_cast<winrt::Windows::Foundation::IReference<bool> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameController2> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameController2>
    {
        std::int32_t __stdcall get_FlashControl(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameFlashControl>(this->shim().FlashControl());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities>
    {
        std::int32_t __stdcall get_Supported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Supported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Min(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().Min());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Max(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().Max());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Step(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().Step());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities>
    {
        std::int32_t __stdcall get_Supported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Supported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Min(float* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<float>(this->shim().Min());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Max(float* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<float>(this->shim().Max());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Step(float* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<float>(this->shim().Step());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl>
    {
        std::int32_t __stdcall get_Value(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<float>>(this->shim().Value());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Value(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Value(*reinterpret_cast<winrt::Windows::Foundation::IReference<float> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameExposureControl> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameExposureControl>
    {
        std::int32_t __stdcall get_Auto(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Auto());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Auto(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Auto(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Value(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<winrt::Windows::Foundation::TimeSpan>>(this->shim().Value());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Value(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Value(*reinterpret_cast<winrt::Windows::Foundation::IReference<winrt::Windows::Foundation::TimeSpan> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities>
    {
        std::int32_t __stdcall get_Supported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Supported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_RedEyeReductionSupported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().RedEyeReductionSupported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PowerSupported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().PowerSupported());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameFlashControl> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameFlashControl>
    {
        std::int32_t __stdcall get_Mode(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameFlashMode>(this->shim().Mode());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Mode(std::int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Mode(*reinterpret_cast<winrt::Windows::Media::Devices::Core::FrameFlashMode const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Auto(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Auto());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Auto(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Auto(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_RedEyeReduction(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().RedEyeReduction());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_RedEyeReduction(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().RedEyeReduction(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PowerPercent(float* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<float>(this->shim().PowerPercent());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_PowerPercent(float value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PowerPercent(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities>
    {
        std::int32_t __stdcall get_Supported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Supported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Min(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().Min());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Max(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().Max());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Step(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().Step());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameFocusControl> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameFocusControl>
    {
        std::int32_t __stdcall get_Value(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<std::uint32_t>>(this->shim().Value());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Value(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Value(*reinterpret_cast<winrt::Windows::Foundation::IReference<std::uint32_t> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities>
    {
        std::int32_t __stdcall get_Supported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Supported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Min(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().Min());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Max(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().Max());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Step(std::uint32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint32_t>(this->shim().Step());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl> : produce_base<D, winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl>
    {
        std::int32_t __stdcall get_Auto(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Auto());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Auto(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Auto(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Value(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<std::uint32_t>>(this->shim().Value());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_Value(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Value(*reinterpret_cast<winrt::Windows::Foundation::IReference<std::uint32_t> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController> : produce_base<D, winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController>
    {
        std::int32_t __stdcall get_Supported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().Supported());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_MaxPhotosPerSecond(float* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<float>(this->shim().MaxPhotosPerSecond());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PhotosPerSecondLimit(float* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<float>(this->shim().PhotosPerSecondLimit());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_PhotosPerSecondLimit(float value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PhotosPerSecondLimit(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetHighestConcurrentFrameRate(void* captureProperties, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::MediaProperties::MediaRatio>(this->shim().GetHighestConcurrentFrameRate(*reinterpret_cast<winrt::Windows::Media::MediaProperties::IMediaEncodingProperties const*>(&captureProperties)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetCurrentFrameRate(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::MediaProperties::MediaRatio>(this->shim().GetCurrentFrameRate());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_FrameCapabilities(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Devices::Core::FrameControlCapabilities>(this->shim().FrameCapabilities());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DesiredFrameControllers(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::Windows::Media::Devices::Core::FrameController>>(this->shim().DesiredFrameControllers());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Media::Devices::Core
{
    inline CameraIntrinsics::CameraIntrinsics(winrt::Windows::Foundation::Numerics::float2 const& focalLength, winrt::Windows::Foundation::Numerics::float2 const& principalPoint, winrt::Windows::Foundation::Numerics::float3 const& radialDistortion, winrt::Windows::Foundation::Numerics::float2 const& tangentialDistortion, std::uint32_t imageWidth, std::uint32_t imageHeight) :
        CameraIntrinsics(impl::call_factory<CameraIntrinsics, ICameraIntrinsicsFactory>([&](ICameraIntrinsicsFactory const& f) { return f.Create(focalLength, principalPoint, radialDistortion, tangentialDistortion, imageWidth, imageHeight); }))
    {
    }
    inline FrameController::FrameController() :
        FrameController(impl::call_factory_cast<FrameController(*)(winrt::Windows::Foundation::IActivationFactory const&), FrameController>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<FrameController>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Media::Devices::Core::ICameraIntrinsics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::ICameraIntrinsics2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::ICameraIntrinsicsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IDepthCorrelatedCoordinateMapper> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameControlCapabilities2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameController> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameController2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameExposureCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameExposureCompensationControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameExposureControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameFlashCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameFlashControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameFocusCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameFocusControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IFrameIsoSpeedControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::IVariablePhotoSequenceController> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::CameraIntrinsics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::DepthCorrelatedCoordinateMapper> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameControlCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameController> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameExposureCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameExposureCompensationCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameExposureCompensationControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameExposureControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameFlashCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameFlashControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameFocusCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameFocusControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameIsoSpeedCapabilities> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::FrameIsoSpeedControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Devices::Core::VariablePhotoSequenceController> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
