// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_ApplicationModel_Contacts_Provider_H
#define WINRT_Windows_ApplicationModel_Contacts_Provider_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.ApplicationModel.Contacts.h"
#include "winrt/impl/Windows.ApplicationModel.Contacts.2.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.ApplicationModel.Contacts.Provider.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::AddContact(param::hstring const& id, winrt::Windows::ApplicationModel::Contacts::Contact const& contact) const
    {
        winrt::Windows::ApplicationModel::Contacts::Provider::AddContactResult winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::AddContact, *(void**)(&id), *(void**)(&contact), reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::RemoveContact(param::hstring const& id) const
    {
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::RemoveContact, *(void**)(&id));
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::ContainsContact(param::hstring const& id) const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::ContainsContact, *(void**)(&id), &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::DesiredFields() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::get_DesiredFields, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<hstring>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::SelectionMode() const
    {
        winrt::Windows::ApplicationModel::Contacts::ContactSelectionMode winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::get_SelectionMode, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::ContactRemoved(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Contacts::Provider::ContactPickerUI, winrt::Windows::ApplicationModel::Contacts::Provider::ContactRemovedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::add_ContactRemoved, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::ContactRemoved(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Contacts::Provider::ContactPickerUI, winrt::Windows::ApplicationModel::Contacts::Provider::ContactRemovedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, ContactRemoved_revoker>(this, ContactRemoved(handler));
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI<D>::ContactRemoved(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>::remove_ContactRemoved, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI2<D>::AddContact(winrt::Windows::ApplicationModel::Contacts::Contact const& contact) const
    {
        winrt::Windows::ApplicationModel::Contacts::Provider::AddContactResult winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2>::AddContact, *(void**)(&contact), reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactPickerUI2<D>::DesiredFieldsWithContactFieldType() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2>::get_DesiredFieldsWithContactFieldType, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVector<winrt::Windows::ApplicationModel::Contacts::ContactFieldType>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactProvider<D>::GetContactFromRemoteIdAsync(param::hstring const& contactRemoteId) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider>::GetContactFromRemoteIdAsync, *(void**)(&contactRemoteId), &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::ApplicationModel::Contacts::Contact>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactProvider<D>::ContactListId() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider>::get_ContactListId, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Contacts_Provider_IContactRemovedEventArgs<D>::Id() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::ApplicationModel::Contacts::Provider::IContactRemovedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Contacts::Provider::IContactRemovedEventArgs>::get_Id, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI> : produce_base<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI>
    {
        std::int32_t __stdcall AddContact(void* id, void* contact, std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::ApplicationModel::Contacts::Provider::AddContactResult>(this->shim().AddContact(*reinterpret_cast<hstring const*>(&id), *reinterpret_cast<winrt::Windows::ApplicationModel::Contacts::Contact const*>(&contact)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall RemoveContact(void* id) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().RemoveContact(*reinterpret_cast<hstring const*>(&id));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall ContainsContact(void* id, bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().ContainsContact(*reinterpret_cast<hstring const*>(&id)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DesiredFields(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<hstring>>(this->shim().DesiredFields());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_SelectionMode(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::ApplicationModel::Contacts::ContactSelectionMode>(this->shim().SelectionMode());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_ContactRemoved(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().ContactRemoved(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Contacts::Provider::ContactPickerUI, winrt::Windows::ApplicationModel::Contacts::Provider::ContactRemovedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_ContactRemoved(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ContactRemoved(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2> : produce_base<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2>
    {
        std::int32_t __stdcall AddContact(void* contact, std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::ApplicationModel::Contacts::Provider::AddContactResult>(this->shim().AddContact(*reinterpret_cast<winrt::Windows::ApplicationModel::Contacts::Contact const*>(&contact)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DesiredFieldsWithContactFieldType(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::Windows::ApplicationModel::Contacts::ContactFieldType>>(this->shim().DesiredFieldsWithContactFieldType());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider> : produce_base<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider>
    {
        std::int32_t __stdcall GetContactFromRemoteIdAsync(void* contactRemoteId, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::ApplicationModel::Contacts::Contact>>(this->shim().GetContactFromRemoteIdAsync(*reinterpret_cast<hstring const*>(&contactRemoteId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ContactListId(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().ContactListId());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactRemovedEventArgs> : produce_base<D, winrt::Windows::ApplicationModel::Contacts::Provider::IContactRemovedEventArgs>
    {
        std::int32_t __stdcall get_Id(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Id());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::ApplicationModel::Contacts::Provider
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Contacts::Provider::IContactPickerUI2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Contacts::Provider::IContactProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Contacts::Provider::IContactRemovedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Contacts::Provider::ContactPickerUI> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Contacts::Provider::ContactRemovedEventArgs> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
