// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_Graphics_Capture_H
#define WINRT_Windows_Graphics_Capture_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.Graphics.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Graphics.2.h"
#include "winrt/impl/Windows.Graphics.DirectX.2.h"
#include "winrt/impl/Windows.Graphics.DirectX.Direct3D11.2.h"
#include "winrt/impl/Windows.Security.Authorization.AppCapabilityAccess.2.h"
#include "winrt/impl/Windows.System.2.h"
#include "winrt/impl/Windows.UI.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.Graphics.Capture.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFrame<D>::Surface() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame>::get_Surface, &winrt_impl_result);
        return winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DSurface{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFrame<D>::SystemRelativeTime() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame>::get_SystemRelativeTime, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFrame<D>::ContentSize() const
    {
        winrt::Windows::Graphics::SizeInt32 winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame>::get_ContentSize, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFrame2<D>::DirtyRegions() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2>::get_DirtyRegions, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Graphics::RectInt32>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFrame2<D>::DirtyRegionMode() const
    {
        winrt::Windows::Graphics::Capture::GraphicsCaptureDirtyRegionMode winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2>::get_DirtyRegionMode, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFrame3<D>::ConfigurationIteration() const
    {
        std::uint64_t winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame3, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame3>::get_ConfigurationIteration, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::Recreate(winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat const& pixelFormat, std::int32_t numberOfBuffers, winrt::Windows::Graphics::SizeInt32 const& size) const
    {
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>::Recreate, *(void**)(&device), static_cast<std::int32_t>(pixelFormat), numberOfBuffers, impl::bind_in(size));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::TryGetNextFrame() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>::TryGetNextFrame, &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::Direct3D11CaptureFrame{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::FrameArrived(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>::add_FrameArrived, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::FrameArrived(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, FrameArrived_revoker>(this, FrameArrived(handler));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::FrameArrived(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>::remove_FrameArrived, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::CreateCaptureSession(winrt::Windows::Graphics::Capture::GraphicsCaptureItem const& item) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>::CreateCaptureSession, *(void**)(&item), &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::GraphicsCaptureSession{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePool<D>::DispatcherQueue() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>::get_DispatcherQueue, &winrt_impl_result);
        return winrt::Windows::System::DispatcherQueue{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePoolStatics<D>::Create(winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat const& pixelFormat, std::int32_t numberOfBuffers, winrt::Windows::Graphics::SizeInt32 const& size) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics>::Create, *(void**)(&device), static_cast<std::int32_t>(pixelFormat), numberOfBuffers, impl::bind_in(size), &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDirect3D11CaptureFramePoolStatics2<D>::CreateFreeThreaded(winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat const& pixelFormat, std::int32_t numberOfBuffers, winrt::Windows::Graphics::SizeInt32 const& size) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics2>::CreateFreeThreaded, *(void**)(&device), static_cast<std::int32_t>(pixelFormat), numberOfBuffers, impl::bind_in(size), &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDisplayGraphicsCaptureSession<D>::SetWindowExclusionList(param::iterable<winrt::Windows::UI::WindowId> const& excludedWindows) const
    {
        std::uint64_t winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession>::SetWindowExclusionList, *(void**)(&excludedWindows), &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IDisplayGraphicsCaptureSession<D>::GetWindowExclusionList() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession>::GetWindowExclusionList, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::WindowId>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureAccessStatics<D>::RequestAccessAsync(winrt::Windows::Graphics::Capture::GraphicsCaptureAccessKind const& request) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureAccessStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureAccessStatics>::RequestAccessAsync, static_cast<std::int32_t>(request), &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Security::Authorization::AppCapabilityAccess::AppCapabilityAccessStatus>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItem<D>::DisplayName() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem>::get_DisplayName, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItem<D>::Size() const
    {
        winrt::Windows::Graphics::SizeInt32 winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem>::get_Size, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItem<D>::Closed(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem>::add_Closed, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItem<D>::Closed(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, Closed_revoker>(this, Closed(handler));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItem<D>::Closed(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem>::remove_Closed, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItemStatics<D>::CreateFromVisual(winrt::Windows::UI::Composition::Visual const& visual) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics>::CreateFromVisual, *(void**)(&visual), &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::GraphicsCaptureItem{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItemStatics2<D>::TryCreateFromWindowId(winrt::Windows::UI::WindowId const& windowId) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2>::TryCreateFromWindowId, impl::bind_in(windowId), &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::GraphicsCaptureItem{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureItemStatics2<D>::TryCreateFromDisplayId(winrt::Windows::Graphics::DisplayId const& displayId) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2>::TryCreateFromDisplayId, impl::bind_in(displayId), &winrt_impl_result);
        return winrt::Windows::Graphics::Capture::GraphicsCaptureItem{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCapturePicker<D>::PickSingleItemAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCapturePicker, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCapturePicker>::PickSingleItemAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession<D>::StartCapture() const
    {
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession>::StartCapture);
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession2<D>::IsCursorCaptureEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2>::get_IsCursorCaptureEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession2<D>::IsCursorCaptureEnabled(bool value) const
    {
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2>::put_IsCursorCaptureEnabled, value);
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession3<D>::IsBorderRequired() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3>::get_IsBorderRequired, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession3<D>::IsBorderRequired(bool value) const
    {
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3>::put_IsBorderRequired, value);
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession4<D>::DirtyRegionMode() const
    {
        winrt::Windows::Graphics::Capture::GraphicsCaptureDirtyRegionMode winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4>::get_DirtyRegionMode, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession4<D>::DirtyRegionMode(winrt::Windows::Graphics::Capture::GraphicsCaptureDirtyRegionMode const& value) const
    {
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4>::put_DirtyRegionMode, static_cast<std::int32_t>(value));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession5<D>::MinUpdateInterval() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5>::get_MinUpdateInterval, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession5<D>::MinUpdateInterval(winrt::Windows::Foundation::TimeSpan const& value) const
    {
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5>::put_MinUpdateInterval, impl::bind_in(value));
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession6<D>::IncludeSecondaryWindows() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6>::get_IncludeSecondaryWindows, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession6<D>::IncludeSecondaryWindows(bool value) const
    {
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6>::put_IncludeSecondaryWindows, value);
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSession7<D>::ConfigurationIteration() const
    {
        std::uint64_t winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession7, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession7>::get_ConfigurationIteration, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Graphics_Capture_IGraphicsCaptureSessionStatics<D>::IsSupported() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Graphics::Capture::IGraphicsCaptureSessionStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Graphics::Capture::IGraphicsCaptureSessionStatics>::IsSupported, &winrt_impl_result);
        return winrt_impl_result;
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame> : produce_base<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame>
    {
        std::int32_t __stdcall get_Surface(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DSurface>(this->shim().Surface());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_SystemRelativeTime(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().SystemRelativeTime());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ContentSize(struct struct_Windows_Graphics_SizeInt32* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Graphics::SizeInt32>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::SizeInt32>(this->shim().ContentSize());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2> : produce_base<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2>
    {
        std::int32_t __stdcall get_DirtyRegions(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Graphics::RectInt32>>(this->shim().DirtyRegions());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DirtyRegionMode(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::GraphicsCaptureDirtyRegionMode>(this->shim().DirtyRegionMode());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame3> : produce_base<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame3>
    {
        std::int32_t __stdcall get_ConfigurationIteration(std::uint64_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint64_t>(this->shim().ConfigurationIteration());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool> : produce_base<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool>
    {
        std::int32_t __stdcall Recreate(void* device, std::int32_t pixelFormat, std::int32_t numberOfBuffers, struct struct_Windows_Graphics_SizeInt32 size) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Recreate(*reinterpret_cast<winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const*>(&device), *reinterpret_cast<winrt::Windows::Graphics::DirectX::DirectXPixelFormat const*>(&pixelFormat), numberOfBuffers, *reinterpret_cast<winrt::Windows::Graphics::SizeInt32 const*>(&size));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryGetNextFrame(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::Direct3D11CaptureFrame>(this->shim().TryGetNextFrame());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_FrameArrived(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().FrameArrived(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_FrameArrived(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().FrameArrived(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall CreateCaptureSession(void* item, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::GraphicsCaptureSession>(this->shim().CreateCaptureSession(*reinterpret_cast<winrt::Windows::Graphics::Capture::GraphicsCaptureItem const*>(&item)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DispatcherQueue(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::System::DispatcherQueue>(this->shim().DispatcherQueue());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics> : produce_base<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics>
    {
        std::int32_t __stdcall Create(void* device, std::int32_t pixelFormat, std::int32_t numberOfBuffers, struct struct_Windows_Graphics_SizeInt32 size, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool>(this->shim().Create(*reinterpret_cast<winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const*>(&device), *reinterpret_cast<winrt::Windows::Graphics::DirectX::DirectXPixelFormat const*>(&pixelFormat), numberOfBuffers, *reinterpret_cast<winrt::Windows::Graphics::SizeInt32 const*>(&size)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics2> : produce_base<D, winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics2>
    {
        std::int32_t __stdcall CreateFreeThreaded(void* device, std::int32_t pixelFormat, std::int32_t numberOfBuffers, struct struct_Windows_Graphics_SizeInt32 size, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool>(this->shim().CreateFreeThreaded(*reinterpret_cast<winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const*>(&device), *reinterpret_cast<winrt::Windows::Graphics::DirectX::DirectXPixelFormat const*>(&pixelFormat), numberOfBuffers, *reinterpret_cast<winrt::Windows::Graphics::SizeInt32 const*>(&size)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession> : produce_base<D, winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession>
    {
        std::int32_t __stdcall SetWindowExclusionList(void* excludedWindows, std::uint64_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint64_t>(this->shim().SetWindowExclusionList(*reinterpret_cast<winrt::Windows::Foundation::Collections::IIterable<winrt::Windows::UI::WindowId> const*>(&excludedWindows)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetWindowExclusionList(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::WindowId>>(this->shim().GetWindowExclusionList());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureAccessStatics> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureAccessStatics>
    {
        std::int32_t __stdcall RequestAccessAsync(std::int32_t request, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Security::Authorization::AppCapabilityAccess::AppCapabilityAccessStatus>>(this->shim().RequestAccessAsync(*reinterpret_cast<winrt::Windows::Graphics::Capture::GraphicsCaptureAccessKind const*>(&request)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureItem> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureItem>
    {
        std::int32_t __stdcall get_DisplayName(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().DisplayName());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Size(struct struct_Windows_Graphics_SizeInt32* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Graphics::SizeInt32>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::SizeInt32>(this->shim().Size());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_Closed(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().Closed(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Graphics::Capture::GraphicsCaptureItem, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_Closed(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Closed(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics>
    {
        std::int32_t __stdcall CreateFromVisual(void* visual, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>(this->shim().CreateFromVisual(*reinterpret_cast<winrt::Windows::UI::Composition::Visual const*>(&visual)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2>
    {
        std::int32_t __stdcall TryCreateFromWindowId(struct struct_Windows_UI_WindowId windowId, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>(this->shim().TryCreateFromWindowId(*reinterpret_cast<winrt::Windows::UI::WindowId const*>(&windowId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryCreateFromDisplayId(struct struct_Windows_Graphics_DisplayId displayId, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>(this->shim().TryCreateFromDisplayId(*reinterpret_cast<winrt::Windows::Graphics::DisplayId const*>(&displayId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCapturePicker> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCapturePicker>
    {
        std::int32_t __stdcall PickSingleItemAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>>(this->shim().PickSingleItemAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession>
    {
        std::int32_t __stdcall StartCapture() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().StartCapture();
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2>
    {
        std::int32_t __stdcall get_IsCursorCaptureEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsCursorCaptureEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_IsCursorCaptureEnabled(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsCursorCaptureEnabled(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3>
    {
        std::int32_t __stdcall get_IsBorderRequired(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsBorderRequired());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_IsBorderRequired(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsBorderRequired(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4>
    {
        std::int32_t __stdcall get_DirtyRegionMode(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Graphics::Capture::GraphicsCaptureDirtyRegionMode>(this->shim().DirtyRegionMode());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_DirtyRegionMode(std::int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DirtyRegionMode(*reinterpret_cast<winrt::Windows::Graphics::Capture::GraphicsCaptureDirtyRegionMode const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5>
    {
        std::int32_t __stdcall get_MinUpdateInterval(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().MinUpdateInterval());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_MinUpdateInterval(std::int64_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MinUpdateInterval(*reinterpret_cast<winrt::Windows::Foundation::TimeSpan const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6>
    {
        std::int32_t __stdcall get_IncludeSecondaryWindows(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IncludeSecondaryWindows());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_IncludeSecondaryWindows(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IncludeSecondaryWindows(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession7> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSession7>
    {
        std::int32_t __stdcall get_ConfigurationIteration(std::uint64_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::uint64_t>(this->shim().ConfigurationIteration());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSessionStatics> : produce_base<D, winrt::Windows::Graphics::Capture::IGraphicsCaptureSessionStatics>
    {
        std::int32_t __stdcall IsSupported(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsSupported());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Graphics::Capture
{
    inline auto Direct3D11CaptureFramePool::Create(winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat const& pixelFormat, std::int32_t numberOfBuffers, winrt::Windows::Graphics::SizeInt32 const& size)
    {
        return impl::call_factory<Direct3D11CaptureFramePool, IDirect3D11CaptureFramePoolStatics>([&](IDirect3D11CaptureFramePoolStatics const& f) { return f.Create(device, pixelFormat, numberOfBuffers, size); });
    }
    inline auto Direct3D11CaptureFramePool::CreateFreeThreaded(winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat const& pixelFormat, std::int32_t numberOfBuffers, winrt::Windows::Graphics::SizeInt32 const& size)
    {
        return impl::call_factory<Direct3D11CaptureFramePool, IDirect3D11CaptureFramePoolStatics2>([&](IDirect3D11CaptureFramePoolStatics2 const& f) { return f.CreateFreeThreaded(device, pixelFormat, numberOfBuffers, size); });
    }
    inline auto GraphicsCaptureAccess::RequestAccessAsync(winrt::Windows::Graphics::Capture::GraphicsCaptureAccessKind const& request)
    {
        return impl::call_factory<GraphicsCaptureAccess, IGraphicsCaptureAccessStatics>([&](IGraphicsCaptureAccessStatics const& f) { return f.RequestAccessAsync(request); });
    }
    inline auto GraphicsCaptureItem::CreateFromVisual(winrt::Windows::UI::Composition::Visual const& visual)
    {
        return impl::call_factory<GraphicsCaptureItem, IGraphicsCaptureItemStatics>([&](IGraphicsCaptureItemStatics const& f) { return f.CreateFromVisual(visual); });
    }
    inline auto GraphicsCaptureItem::TryCreateFromWindowId(winrt::Windows::UI::WindowId const& windowId)
    {
        return impl::call_factory<GraphicsCaptureItem, IGraphicsCaptureItemStatics2>([&](IGraphicsCaptureItemStatics2 const& f) { return f.TryCreateFromWindowId(windowId); });
    }
    inline auto GraphicsCaptureItem::TryCreateFromDisplayId(winrt::Windows::Graphics::DisplayId const& displayId)
    {
        return impl::call_factory<GraphicsCaptureItem, IGraphicsCaptureItemStatics2>([&](IGraphicsCaptureItemStatics2 const& f) { return f.TryCreateFromDisplayId(displayId); });
    }
    inline GraphicsCapturePicker::GraphicsCapturePicker() :
        GraphicsCapturePicker(impl::call_factory_cast<GraphicsCapturePicker(*)(winrt::Windows::Foundation::IActivationFactory const&), GraphicsCapturePicker>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<GraphicsCapturePicker>(); }))
    {
    }
    inline auto GraphicsCaptureSession::IsSupported()
    {
        return impl::call_factory_cast<bool(*)(IGraphicsCaptureSessionStatics const&), GraphicsCaptureSession, IGraphicsCaptureSessionStatics>([](IGraphicsCaptureSessionStatics const& f) { return f.IsSupported(); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFrame3> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePool> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IDisplayGraphicsCaptureSession> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureAccessStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureItem> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureItemStatics2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCapturePicker> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession3> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession4> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession5> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession6> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSession7> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::IGraphicsCaptureSessionStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::Direct3D11CaptureFrame> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::GraphicsCaptureAccess> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::GraphicsCaptureItem> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::GraphicsCapturePicker> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Graphics::Capture::GraphicsCaptureSession> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
