// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Windows_Media_Control_H
#define WINRT_Windows_Media_Control_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/Windows.Media.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Media.2.h"
#include "winrt/impl/Windows.Storage.Streams.2.h"
#include "winrt/impl/Windows.Media.Control.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::SourceAppUserModelId() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::get_SourceAppUserModelId, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryGetMediaPropertiesAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryGetMediaPropertiesAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionMediaProperties>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::GetTimelineProperties() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::GetTimelineProperties, &winrt_impl_result);
        return winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionTimelineProperties{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::GetPlaybackInfo() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::GetPlaybackInfo, &winrt_impl_result);
        return winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackInfo{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryPlayAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryPlayAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryPauseAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryPauseAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryStopAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryStopAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryRecordAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryRecordAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryFastForwardAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryFastForwardAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryRewindAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryRewindAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TrySkipNextAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TrySkipNextAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TrySkipPreviousAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TrySkipPreviousAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryChangeChannelUpAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryChangeChannelUpAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryChangeChannelDownAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryChangeChannelDownAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryTogglePlayPauseAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryTogglePlayPauseAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryChangeAutoRepeatModeAsync(winrt::Windows::Media::MediaPlaybackAutoRepeatMode const& requestedAutoRepeatMode) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryChangeAutoRepeatModeAsync, static_cast<std::int32_t>(requestedAutoRepeatMode), &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryChangePlaybackRateAsync(double requestedPlaybackRate) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryChangePlaybackRateAsync, requestedPlaybackRate, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryChangeShuffleActiveAsync(bool requestedShuffleState) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryChangeShuffleActiveAsync, requestedShuffleState, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TryChangePlaybackPositionAsync(std::int64_t requestedPlaybackPosition) const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::TryChangePlaybackPositionAsync, requestedPlaybackPosition, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TimelinePropertiesChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::TimelinePropertiesChangedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::add_TimelinePropertiesChanged, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TimelinePropertiesChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::TimelinePropertiesChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, TimelinePropertiesChanged_revoker>(this, TimelinePropertiesChanged(handler));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::TimelinePropertiesChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::remove_TimelinePropertiesChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::PlaybackInfoChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::PlaybackInfoChangedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::add_PlaybackInfoChanged, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::PlaybackInfoChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::PlaybackInfoChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, PlaybackInfoChanged_revoker>(this, PlaybackInfoChanged(handler));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::PlaybackInfoChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::remove_PlaybackInfoChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::MediaPropertiesChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::MediaPropertiesChangedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::add_MediaPropertiesChanged, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::MediaPropertiesChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::MediaPropertiesChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, MediaPropertiesChanged_revoker>(this, MediaPropertiesChanged(handler));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSession<D>::MediaPropertiesChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>::remove_MediaPropertiesChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::GetCurrentSession() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>::GetCurrentSession, &winrt_impl_result);
        return winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::GetSessions() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>::GetSessions, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::CurrentSessionChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager, winrt::Windows::Media::Control::CurrentSessionChangedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>::add_CurrentSessionChanged, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::CurrentSessionChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager, winrt::Windows::Media::Control::CurrentSessionChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, CurrentSessionChanged_revoker>(this, CurrentSessionChanged(handler));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::CurrentSessionChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>::remove_CurrentSessionChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::SessionsChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager, winrt::Windows::Media::Control::SessionsChangedEventArgs> const& handler) const
    {
        winrt::event_token winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>::add_SessionsChanged, *(void**)(&handler), put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::SessionsChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager, winrt::Windows::Media::Control::SessionsChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, SessionsChanged_revoker>(this, SessionsChanged(handler));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManager<D>::SessionsChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>::remove_SessionsChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionManagerStatics<D>::RequestAsync() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManagerStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManagerStatics>::RequestAsync, &winrt_impl_result);
        return winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::Title() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_Title, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::Subtitle() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_Subtitle, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::AlbumArtist() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_AlbumArtist, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::Artist() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_Artist, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::AlbumTitle() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_AlbumTitle, &winrt_impl_result);
        return hstring{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::TrackNumber() const
    {
        std::int32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_TrackNumber, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::Genres() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_Genres, &winrt_impl_result);
        return winrt::Windows::Foundation::Collections::IVectorView<hstring>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::AlbumTrackCount() const
    {
        std::int32_t winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_AlbumTrackCount, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::PlaybackType() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_PlaybackType, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<winrt::Windows::Media::MediaPlaybackType>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionMediaProperties<D>::Thumbnail() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>::get_Thumbnail, &winrt_impl_result);
        return winrt::Windows::Storage::Streams::IRandomAccessStreamReference{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsPlayEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsPlayEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsPauseEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsPauseEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsStopEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsStopEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsRecordEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsRecordEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsFastForwardEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsFastForwardEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsRewindEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsRewindEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsNextEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsNextEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsPreviousEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsPreviousEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsChannelUpEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsChannelUpEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsChannelDownEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsChannelDownEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsPlayPauseToggleEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsPlayPauseToggleEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsShuffleEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsShuffleEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsRepeatEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsRepeatEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsPlaybackRateEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsPlaybackRateEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackControls<D>::IsPlaybackPositionEnabled() const
    {
        bool winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>::get_IsPlaybackPositionEnabled, &winrt_impl_result);
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackInfo<D>::Controls() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>::get_Controls, &winrt_impl_result);
        return winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackControls{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackInfo<D>::PlaybackStatus() const
    {
        winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackStatus winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>::get_PlaybackStatus, reinterpret_cast<std::int32_t*>(&winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackInfo<D>::PlaybackType() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>::get_PlaybackType, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<winrt::Windows::Media::MediaPlaybackType>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackInfo<D>::AutoRepeatMode() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>::get_AutoRepeatMode, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<winrt::Windows::Media::MediaPlaybackAutoRepeatMode>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackInfo<D>::PlaybackRate() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>::get_PlaybackRate, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<double>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionPlaybackInfo<D>::IsShuffleActive() const
    {
        void* winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>::get_IsShuffleActive, &winrt_impl_result);
        return winrt::Windows::Foundation::IReference<bool>{ winrt_impl_result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionTimelineProperties<D>::StartTime() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>::get_StartTime, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionTimelineProperties<D>::EndTime() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>::get_EndTime, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionTimelineProperties<D>::MinSeekTime() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>::get_MinSeekTime, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionTimelineProperties<D>::MaxSeekTime() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>::get_MaxSeekTime, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionTimelineProperties<D>::Position() const
    {
        winrt::Windows::Foundation::TimeSpan winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>::get_Position, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
    template <typename D> auto consume_Windows_Media_Control_IGlobalSystemMediaTransportControlsSessionTimelineProperties<D>::LastUpdatedTime() const
    {
        winrt::Windows::Foundation::DateTime winrt_impl_result{};
        consume_general<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>::get_LastUpdatedTime, put_abi(winrt_impl_result));
        return winrt_impl_result;
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::ICurrentSessionChangedEventArgs> : produce_base<D, winrt::Windows::Media::Control::ICurrentSessionChangedEventArgs>
    {
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession>
    {
        std::int32_t __stdcall get_SourceAppUserModelId(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().SourceAppUserModelId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryGetMediaPropertiesAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionMediaProperties>>(this->shim().TryGetMediaPropertiesAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetTimelineProperties(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionTimelineProperties>(this->shim().GetTimelineProperties());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetPlaybackInfo(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackInfo>(this->shim().GetPlaybackInfo());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryPlayAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryPlayAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryPauseAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryPauseAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryStopAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryStopAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryRecordAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryRecordAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryFastForwardAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryFastForwardAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryRewindAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryRewindAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TrySkipNextAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TrySkipNextAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TrySkipPreviousAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TrySkipPreviousAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryChangeChannelUpAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryChangeChannelUpAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryChangeChannelDownAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryChangeChannelDownAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryTogglePlayPauseAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryTogglePlayPauseAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryChangeAutoRepeatModeAsync(std::int32_t requestedAutoRepeatMode, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryChangeAutoRepeatModeAsync(*reinterpret_cast<winrt::Windows::Media::MediaPlaybackAutoRepeatMode const*>(&requestedAutoRepeatMode)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryChangePlaybackRateAsync(double requestedPlaybackRate, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryChangePlaybackRateAsync(requestedPlaybackRate));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryChangeShuffleActiveAsync(bool requestedShuffleState, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryChangeShuffleActiveAsync(requestedShuffleState));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TryChangePlaybackPositionAsync(std::int64_t requestedPlaybackPosition, void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<bool>>(this->shim().TryChangePlaybackPositionAsync(requestedPlaybackPosition));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_TimelinePropertiesChanged(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().TimelinePropertiesChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::TimelinePropertiesChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_TimelinePropertiesChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().TimelinePropertiesChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_PlaybackInfoChanged(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().PlaybackInfoChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::PlaybackInfoChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_PlaybackInfoChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PlaybackInfoChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_MediaPropertiesChanged(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().MediaPropertiesChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession, winrt::Windows::Media::Control::MediaPropertiesChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_MediaPropertiesChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MediaPropertiesChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager>
    {
        std::int32_t __stdcall GetCurrentSession(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession>(this->shim().GetCurrentSession());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetSessions(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession>>(this->shim().GetSessions());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_CurrentSessionChanged(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().CurrentSessionChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager, winrt::Windows::Media::Control::CurrentSessionChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_CurrentSessionChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CurrentSessionChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_SessionsChanged(void* handler, winrt::event_token* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::event_token>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::event_token>(this->shim().SessionsChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager, winrt::Windows::Media::Control::SessionsChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_SessionsChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SessionsChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManagerStatics> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManagerStatics>
    {
        std::int32_t __stdcall RequestAsync(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager>>(this->shim().RequestAsync());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties>
    {
        std::int32_t __stdcall get_Title(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Title());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Subtitle(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Subtitle());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_AlbumArtist(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().AlbumArtist());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Artist(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().Artist());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_AlbumTitle(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<hstring>(this->shim().AlbumTitle());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_TrackNumber(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::int32_t>(this->shim().TrackNumber());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Genres(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<hstring>>(this->shim().Genres());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_AlbumTrackCount(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<std::int32_t>(this->shim().AlbumTrackCount());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PlaybackType(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<winrt::Windows::Media::MediaPlaybackType>>(this->shim().PlaybackType());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Thumbnail(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Storage::Streams::IRandomAccessStreamReference>(this->shim().Thumbnail());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls>
    {
        std::int32_t __stdcall get_IsPlayEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsPlayEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsPauseEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsPauseEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsStopEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsStopEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsRecordEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsRecordEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsFastForwardEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsFastForwardEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsRewindEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsRewindEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsNextEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsNextEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsPreviousEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsPreviousEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsChannelUpEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsChannelUpEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsChannelDownEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsChannelDownEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsPlayPauseToggleEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsPlayPauseToggleEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsShuffleEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsShuffleEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsRepeatEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsRepeatEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsPlaybackRateEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsPlaybackRateEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsPlaybackPositionEnabled(bool* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<bool>(this->shim().IsPlaybackPositionEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo>
    {
        std::int32_t __stdcall get_Controls(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackControls>(this->shim().Controls());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PlaybackStatus(std::int32_t* winrt_impl_result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackStatus>(this->shim().PlaybackStatus());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PlaybackType(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<winrt::Windows::Media::MediaPlaybackType>>(this->shim().PlaybackType());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_AutoRepeatMode(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<winrt::Windows::Media::MediaPlaybackAutoRepeatMode>>(this->shim().AutoRepeatMode());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_PlaybackRate(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<double>>(this->shim().PlaybackRate());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsShuffleActive(void** winrt_impl_result) noexcept final try
        {
            clear_abi(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::IReference<bool>>(this->shim().IsShuffleActive());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties> : produce_base<D, winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties>
    {
        std::int32_t __stdcall get_StartTime(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().StartTime());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_EndTime(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().EndTime());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_MinSeekTime(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().MinSeekTime());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_MaxSeekTime(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().MaxSeekTime());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Position(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::TimeSpan>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::TimeSpan>(this->shim().Position());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_LastUpdatedTime(std::int64_t* winrt_impl_result) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::DateTime>(winrt_impl_result);
            typename D::abi_guard guard(this->shim());
            *winrt_impl_result = detach_from<winrt::Windows::Foundation::DateTime>(this->shim().LastUpdatedTime());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IMediaPropertiesChangedEventArgs> : produce_base<D, winrt::Windows::Media::Control::IMediaPropertiesChangedEventArgs>
    {
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::IPlaybackInfoChangedEventArgs> : produce_base<D, winrt::Windows::Media::Control::IPlaybackInfoChangedEventArgs>
    {
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::ISessionsChangedEventArgs> : produce_base<D, winrt::Windows::Media::Control::ISessionsChangedEventArgs>
    {
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Media::Control::ITimelinePropertiesChangedEventArgs> : produce_base<D, winrt::Windows::Media::Control::ITimelinePropertiesChangedEventArgs>
    {
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Media::Control
{
    inline auto GlobalSystemMediaTransportControlsSessionManager::RequestAsync()
    {
        return impl::call_factory_cast<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager>(*)(IGlobalSystemMediaTransportControlsSessionManagerStatics const&), GlobalSystemMediaTransportControlsSessionManager, IGlobalSystemMediaTransportControlsSessionManagerStatics>([](IGlobalSystemMediaTransportControlsSessionManagerStatics const& f) { return f.RequestAsync(); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Media::Control::ICurrentSessionChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSession> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionManagerStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionMediaProperties> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackControls> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionPlaybackInfo> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IGlobalSystemMediaTransportControlsSessionTimelineProperties> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IMediaPropertiesChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::IPlaybackInfoChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::ISessionsChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::ITimelinePropertiesChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::CurrentSessionChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionMediaProperties> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackControls> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionPlaybackInfo> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSessionTimelineProperties> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::MediaPropertiesChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::PlaybackInfoChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::SessionsChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Media::Control::TimelinePropertiesChangedEventArgs> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
